# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82921481652f2841855201248204b94123d1ae21aa6e25120e41be8d447bec49d8bf08696d3c2198c1c2b1cde66fc0bc701ef9b3d043fa62b322e500254cfe21

test:
  secret_key_base: 4dd4622fdafadbc5e1aad260e2784053711a407024923338145cb06a569cb162d95678dfce8f3573a1e1373e233b602aa1ffa8bca60e35c120c9a9cf727c4daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
